# DataSource settings: set here your own configurations for the database connection.
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.0.103:3306/needy?autoReconnect=true&useSSL=false&useUnicode=true&amp;characterEncoding=UTF-8&useLegacyDatetimeCode=false
  username: root
  password: root
  connectionProperties: useUnicode=true;characterEncoding=utf-8;CharSet=utf8mb4 

# Configuration of Redis Database
redis:
  host: localhost
  port: 6379
  timeout: 60000
  pool: 
    maxidle: 100
    minidle: 0
    maxactive: 1000

# config context path to "/" by setting an empty string
server:
  contextPath: /v1

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

## Resource
resource_dir:
  images: /home/lion

#Application configurations
needy:
  # Token
  token:
    header: Authorization
    prefix: Bearer
    secret: thisIsSecret
    expiration: 604800
  identification:
    header: ID
  # Firebase
  firebase:
    path: firebase/needyfirebase.json
    database:
      url: https://needy-180007.firebaseio.com
  # Router
  route:
    securities:
      authentications: authentications # POST - login
      refreshments: refreshments # GET - get new token
      #logout: logout

    users:
      registers: users/news # POST - register account
      find: users/find #?username= |GET - Check account exist
      reset: users/reset #?username= |POST - reset password
      #passwords:
      #  update: users/{username}/passwords #PUT: update pass
      informations: users # GET get account info DELETE: delete account
      #active: users/activeness # POST active user account

    companies:
      infomation: companies # GET
      #dependencies: companies/dependencies # GET
      registers: companies # POST - post new company
      #staffs:
      #  fcms: companies/{company_id}/staffs/fcm_tokens # PUT update token

    stores:
      infomation: stores # GET

    categories:
      lists: categories/{category} #?company_id= |GET - get link categories of category and company
                                      # |GET - get all link categories of category

    products:
      price_now:
        add_new: pn/products #?company_id=&store_id= |POST - add new product
        images:
          add_new: pn/products/{product_id}/images #?multiparty= |POST - add image for product
          update: pn/products/{product_id}/images #?multiparty= |PUT - update image for product

    attributes:
      lists: attributes #?category_name= |GET - all attribute of category