# DataSource settings: set here your own configurations for the database connection.
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.0.103:3306/needy?autoReconnect=true&useSSL=false&useUnicode=true&amp;characterEncoding=UTF-8&useLegacyDatetimeCode=false
  username: root
  password: root
  connectionProperties: useUnicode=true;characterEncoding=utf-8;CharSet=utf8mb4 

# Configuration of Redis Database
redis:
  host: 192.168.0.103
  port: 6379
  timeout: 60000
  pool: 
    maxidle: 100
    minidle: 0
    maxactive: 1000

# config context path to "/" by setting an empty string
server:
  contextPath: /

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

## Resource
resource_dir:
  images: /home/lion

#Application configurations
needy:
  # Token
  token:
    header: Authorization
    prefix: Bearer
    secret: thisIsSecret
    expiration: 604800
  identification:
    header: ID
  # Firebase
  firebase:
    path: firebase/needyfirebase.json
    database:
      url: https://needy-180007.firebaseio.com
  # Router
  # Note: [____] = OPTION
  route:
    v1:
      users:
        #POST - login
        login: v1/authentications
        #GET - get new token
        refreshments: v1/refreshments
        #GET - logout system
        logout: v1/exitses
        #POST - register account
        registers: v1/users
        #GET - check account exist
        find_username_exist: v1/users/finds #?username=
        #POST - reset password
        reset_account: v1/users/resets #?username=
        #GET  - get self user info
        #self: users
        #GET   - get user info details
        information_details: v1/users/informations/details
        #PUT update info account
        update_information_details: v1/users/informations/details
        #GET   - get business information
        business_information: v1/users/businesses/informations

      companies:
        #GET check company where user is working
        find_our_company: v1/companies/users
        #GET - get company
        information_details: v1/companies/{company_id}/informations/details
        #POST - register new company
        registers: v1/companies
        #PUT - update company info
        update_information_details: v1/companies/{company_id}/informations/details

      categories:
        #GET - get link categories of category and company
        get_lists: v1/categories/{category}/childs #[?company_id]=

      attributes:
        #GET - get all attribute of category
        get_lists: v1/attributes/lists #?category_name=

      stores:
        #GET check st where user is working
        find_our_store: v1/stores/users
        #GET - get store info details
        information_details: v1/stores/{store_id}/infomations/details
        #PUT - update store info
        update_information_details: v1/stores/{store_id}/infomations/details


      products:
        price_now:
          add_new: v1/pn/products #?company_id=&store_id= |POST - add new product
          images:
            add_new: pn/products/{product_id}/images #?multiparty= |POST - add image for product
            update: pn/products/{product_id}/images #?multiparty= |PUT - update image for product

    v2: v2